### ISSUE TITLE
Animation tutorial

### ISSUE THREAD

**Issue by amorenew** [flyingV805/AnimatedStarsFlutter#2]
Hello,

What should I need to learn to be able to make advanced animation and calculations like this library?

Thanks

**Comment by flyingV805** [comment]
Hey! 

To be honest, no complex structures are used here. Basic knowledge of algorithms and data structures is more than enough. Briefly what is happening:

0. We get the canvas on which the display takes place (custom painter)
1. Choose a random point (random X, random Y in range of view height and width)
2. "Fire" the star (create a star object using the coordinates from the previous step)
3. When the star "fade out" - remove it and "Fire" a new one
4. repeat

**Comment by amorenew** [comment]
Thanks a lot Vladislav Petrov
